Fix snapshot recovery of established network connections, and more
kontainapp/km pull request #1694
Opened 2022-10-27 16:49 UTC by paulpopelka

This change started out to fix the problem of connections that are establish when a snapshot is taken should be recovered as unconnected and return an error when a system call using the now disconnection connection. That is fixed but more stuff ended up being piled in here. The other stuff fixed is:

- clear the error field of the km_file_t when a file is opened. It should probably be cleared after an error is returned but this fix is already pretty big.

- Add tests to tests/snapshot_test.c to verify that socket bound addresses are being recovered.

- Reduce the number of values used to describe how an fd came into existence and the state of a socket.  Formerly there were values stored in the km_file_t an the km_fd_socket_t and in the snapshot elf notes.  Now we only use the km_file_t and km_fd_socket_t values in km_file_t and the elf notes.

- a socket with a local address bound is not really in a different state.  We were representing such sockets as being in a different state.  Being bound is just a property of a socket.  If you read the ip(7) man page you will find that binding an address is not required for a listen to be performed and you can bind a local address to a socket that will never be performing a connect.  The code in snapshot is changed to treat the bound local address as a socket property now.

- the shutdown() system call changes the "connected" state of a socket. km was not handling this at all.  It does now.

2022-10-27 20:42 UTC, paulpopelka commented
Fixes PR #1661

2022-10-27 21:32 UTC, paulpopelka commented
A note to myself for the flleeting exit thread test failure:
```
not ok 365 threads_exit_grp(glibc_static): force exit when threads are in flight (exit_grp_test.fedora)
# (from function `assert' in file bats-assert/src/assert.bash, line 46,
#  in test file km-bats-7.glibc_static, line 641)
#   `assert [ $status -eq 17 -o $status -eq 11  ]' failed with status 134
# start: 2022-10-27 16:59:25.185591119+00:00 threads_exit_grp(glibc_static): force exit when threads are in flight (exit_grp_test.fedora)
# --- Test script output:
# 
# -- assertion failed --
# expression : [ 134 -eq 17 -o 134 -eq 11 ]
# --
# 
#   end: 2022-10-27 16:59:28.621158857+00:00 threads_exit_grp(glibc_static): force exit when threads are in flight (exit_grp_test.fedora)
# 
# --- Command line:
# km_with_timeout exit_grp_test.fedora
# --- Command output:
# .16:59:28.184711 km_dump_core         875  vcpu-9  Writing coredump to './kmcore'
# 16:59:28.583468 km_deliver_signal    624  vcpu-9  guest: Terminated by signal: Aborted (core dumped)
# 
# Killed by signal. Timeout returns 134: /home/appuser/km/build/opt/kontain/bin/km --virt-device=/dev/kvm --km-log-to=stderr   exit_grp_test.fedora
# ---
```

2022-10-27 22:12 UTC, gnode1 commented on km/km_filesys.c
> +      sock->state = KM_SOCK_STATE_CONNECTED;
Same in accept4?

2022-10-27 22:17 UTC, gnode1 commented on km/km_filesys.c
> +   if (ret == 0 && sock->state != KM_SOCK_STATE_UNCONNECTED) {
I wonder if we should do this for ENOTCONN?

2022-10-27 22:17 UTC, gnode1 commented on km/km_filesys.c
> +#if 0
debug cruft?

2022-10-27 22:18 UTC, gnode1 commented on km/km_filesys.c
> +   sock->state = KM_SOCK_STATE_CONNECTED;
Same in accept4?

2022-10-27 22:26 UTC, gnode1 requested changes
Generally looks good, there is one question about accept4, and a couple of nits

2022-10-27 22:53 UTC, paulpopelka commented
Please ignore all that stuff in the review I apparently started.

2022-11-11 18:12 UTC, paulpopelka commented
This change was absorbed into another change which has been merged.
This will be closed as not needed.

2022-11-11 18:12 UTC, closed without merging